language: python
python:
  - "3.7"
  - "3.8"
before_install:
  - pip install -r requirements.txt
script:
  - make test
  - make check
after_success:
  - make testcov
env:
  global:
    secure: dBuQ4M0L2PnunsFKFXnx2EuidFrUv6c7p2srMPn9toWLk35dTlYqD1XtLbTqg/nw9z6ohGX9ypmg7BCAA3oo8Z4F0VjIOjSXPHy1XoTVQIsS42Ky9MguCYW81KkriUnT2ycuRU+i2FoO9N8yObRzPs9pv3QYgWUbIwZXFc9sPbGvX8/8CVN4rl3JUcooIV5za89dXGP4OvT3PE4pTAUa1y+aKIeuQKDbNU+i+Ycuk685gkhBWfhVKjT/1fk2jnTCPosvC+PH4yN2d4GJl8vxBPBL+iqKrhYiHZe3/96gpov6YXymaDwfp62eMIKUaDyb7jng+qXNcqsGsrawP9LDMd+pTn0323ha7lHuCbvC3wgdwRwpBY+xcKcZf9++VMUW9y7bHxCSWDXxu8xk9y3pKwAaL+hmG4LVX5FlBka4AnVOk3eKspHYjQNx7pp7AwZHtlqbPDpSngROuH1y46388qySsKyKXk/6tLS3ZpZ2B2jvbn+dX1jOJfknBihlOvp4ZSSRRroaHhqTEMPkLuEB4JqoNIm4RTkeIQyILt2EOADmzSefErwH6BV9xrLJOwVCj3pjY5DW4rUPxPhNqlqJuCv15ADkb31+U8b2/Fgp2u3K4U6MvLiEarCp8HoHrXVRGk+p7JqX8KNN4zkYsI2KKjmqm4tuiKF8MgRusH+Q8I0=

install:
  bash <(curl -s https://codecov.io/bash)