language: python
python:
  - "3.7"
  - "3.8"
before_install:
  - pip install -r requirements.txt
script:
  - make test
  - make check
after_success:
  - make testcov

env:
  global:
    secure: jG+sx0/AVAWlVKwyTNpD9D0pj8hwVJpC1iGpcYUdMm51rFHyBoD17+gdFYKhwdwt+ZOliSUQ3n3+dFNUeUswPIF9l+y3Sso7zHI3vjSzFWdNWUXQgaKZHGwh6cEno0h391f+Uh4tyqQ4LR+GnWea/shYIFadMBkrDWlO1iH7FM4L4NsmxjD6/In5UzK19Vl1xYg4/sjNYPm/6CaCyFjrLo6ijpjtdbCf9R/5nIEDyXRJVMYmI2k4xQioqIhTcvK21R9UjCLSYTA2oifmn7dUqNegH+PXoAaBEmROm2R6wwG4GKyqDbk1KIGm8Di1HNw87jHlqyu/bdZl9yFX9yjkIeD+vRJKztoJu/WtI7lbX7ZN/0D+NGCkHMEviaUAZC4JSgnT5fJlswGQgQSaEkMJ/CQQTjtn0v2t7rF9lztfgn0t7ayJ54aakQ8ylgbUFWrI9ArCnYpZyZv+Sp+QwCx6SH3UVFKePGJOta/EL3Nq9mDQW4lo75+v6TJByZe8x9wwyKOvvbw05QEvkPo/VRBH34IjNdbqDZg745jn5aC3Y4xJDRtcSq33AMT0xNJ4x00A3FR8cX2w3jPWYuxm40yd7c3Cvr2FkIxRD58YQfd3Wkm1UH4rfzrO3on/cS9TuQiBfwSP2v1np6lAElkuRGqZbgNkj3j9vfJ3L2HsEEHxF1k=

install:
 - coveralls
